dist: xenial
os: linux
language: node_js
node_js:
  - 12

branches:
  only:
    - master # build master branch only

before_install:
  - npm install hexo-cli        # install hexo

install:
  - npm install

script:                         
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  strategy: git
  token: $GH_TOKEN
  keep_history: true
  local_dir: public
  target_branch: gh-pages