name: Sync static file to home.ustc.edu.cn
on:
  push:
    branches:
      - master

env:
  DEPLOY_REPO: thisiszy/thisiszy.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .
          submodules: recursive

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies && Generate hexo
        run: |
          ls -a
          npm install
          npm install hexo-cli -g
          rm _config.yml
          mv config2.yml _config.yml
          hexo generate
          git reset --hard

      - name: FTP-Deploy
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp://home.ustc.edu.cn/
          user: ${{ secrets.HEXO_DEPLOY_USER }}
          password: ${{ secrets.HEXO_DEPLOY_PWD }}
          localDir: public
          remoteDir: public_html
          forceSsl: true