name: Sync static file to home.ustc.edu.cn
on:
  push:
    branches:
      - master

env:
  DEPLOY_REPO: thisiszy/thisiszy.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git
          submodules: true

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy hexo
        run: |
          npm install hexo-cli -g
          hexo generate
          ls
          git reset --hard

      - name: FTP-Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://home.ustc.edu.cn/
          ftp-username: ${{ secrets.HEXO_DEPLOY_USER }}
          ftp-password: ${{ secrets.HEXO_DEPLOY_PWD }}
          local-dir: public
          remoteDir: public
          forceSsl: true